### ISSUE TITLE
Création de produit et service à l'activation du module

### ISSUE THREAD

**Issue by altairis-tof** [Evarisk/DoliSIRH#10]
Bonjour,
J'ai mis en prod DoliSIRH ce dimanche sur le dolibarr d'altairis pour remplacer Doliproject.
Lundi, on s'est aperçu qu'on avait des produits et services (Primes spéciales, 13ème mois et autres joyeusetés - carrément un projet RH altairis qui est apparu sans qu'on lui demande rien) qui avaient été créés dans notre base sans qu'on ait rien demandé, tous à la date de dimanche 10h03 !
J'ai parcouru le code d'init du module en vitesse sans trouver l'origine du délire.
Est ce que ça vous dit quelque chose ?
@lmag ?

**Comment by altairis-tof** [comment]
Update : j'ai installé dolisirh parce que @lmag  m'a dit que ça remplace doliproject, mais je ne comprends pas trop l'utilité des navettes et tout le reste pour ceux qui veulent seulement des fonctions de base de doliproject (liaison temps consommé/tickets) ! J'ai l'impression d'avoir installé une usine à gaz qui va croître exponentiellement sans en connaître les tenants et les aboutissants; je vois même passer des histoires de framework dans une issue (la #5 ). 
Avez vous une roadmap de la bête ? 
Ne devrais je pas plutôt rester sur doliproject pour mes petits besoins ??? (quitte à faire évoluer mon fork indépendamment de dolisirh ?)

**Comment by lmag** [comment]
Bonjour Christophe,
L'idée initial de Doliproject est d'avoir une vu assez simple sur le temps que l'on passe sur les projets en s'appuyant au maximum sur les objects Dolibarr

- Projets
- Taches
- Temps noté
- Services facturés avec du temps

Nous avons déterminé un projet standard afin que les temps qui ne sont pas consacrés au travail puisse être noté

- Projet standard RH

Le projet prend effectivement une autre dimension, cependant il n'a pas vocation a être trop complexe il doit nous permettre de :

- Suivre le temps passé simplement (avec les taches favorites ! C'est super simple)
- Permettre la préparation de la navette pour la paye en mode simple (C'est pour notre assistance qui ne veut plus le faire à la main)
- Permettre un récap du temps passé sur projet afin d'isoler les couts de MO (C'est pour les financements CII)
- Créer des taches automatiquement entre des factures avec du temps et des taches (projet initial et fonctionnement lorsque l'on vend du SAV mensuel annuel etc..)

Nous avons échangé avec @FHenry sur la pertinence du nom et DoliSIRH nous semble bien plus adapté à terme

**Comment by altairis-tof** [comment]
Bonjour Laurent,
Je comprends le principe; c'est juste très surprenant que des projets, produits et service soient créés automatiquement sans qu'on en soit informé (ou qu'on en ait besoin).
Je pense qu'il serait bien qu'il y ait plutôt un paramétrage du module pour cela.
Idem pour les histoires de navettes qui correspondent à un cas d'usage pas forcément adapté à toutes les sociétés ;-)
Et désolé d'avoir été un peu vif dans mon premier message mais met toi à notre place quand on a découvert ces nouveaux projets, produits et services dans notre Dolibarr ! on a eu peur d'une malveillance avant de penser que ça pouvait être lié à votre module !
