### ISSUE TITLE
remonter les évènements des factures (notamment les relances) dans le pointage de temps

### ISSUE THREAD

**Issue by ocemag** [Evarisk/DoliSIRH#122]
80f432b31af310736c79e2efed180f90f88bdd86
Lorsqu'on relance une facture, si on a passé 1h au téléphone avec le client on le note dans les évènements de la facture. Est-ce que ces temps peuvent être remontés dans le pointage de temps?

**Comment by evarisk-theo** [comment]
Case à cocher "pointer le temps", si cochée on pointe le temps dans la tâche sélectionnée
